import "@/components/burger/index";
import "@/components/slider/index";
import "@/sites/FantasyHub/components/counter/index";
import "@/sites/FantasyHub/components/faq/index";
import "@/sites/FantasyHub/components/inspiring/index";
import "@/sites/FantasyHub/components/reveal/index";
import "@/sites/FantasyHub/components/disclaimer-modal/index";
import "@/components/parallax/index";
import "@/components/dev-land/index";
